# Generated by Django 4.2.5 on 2023-09-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=18)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=12)),
            ],
        ),
    ]
