# Generated by Django 4.2.5 on 2023-09-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='token_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='verify_user',
            field=models.BooleanField(default=False),
        ),
    ]
