# Generated by Django 4.2.5 on 2023-09-14 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
