# Generated by Django 4.2.5 on 2023-09-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0003_rename_passwprd_ownercar_ownercar_password_ownercar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownercar',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
