# Generated by Django 4.2.5 on 2023-09-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0004_ownercar_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownercar',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
