# Generated by Django 4.2.5 on 2023-09-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0005_ownercar_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownercar',
            name='custom_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
