# Generated by Django 4.2.5 on 2023-09-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0006_ownercar_custom_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownercar',
            name='custom_authenticated',
        ),
    ]
