# Generated by Django 4.2.5 on 2023-10-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0008_carowner_rename_ownercar_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='img_customer',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
