# Generated by Django 4.2.5 on 2023-09-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarownerApp', '0003_driver_comfirm_account_driver_email_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_schedule', models.CharField(max_length=255, null=True)),
                ('start_location', models.CharField(max_length=255, null=True)),
                ('end_location', models.CharField(max_length=255, null=True)),
                ('start_date_time', models.DateTimeField(null=True)),
                ('end_date_time', models.DateTimeField(null=True)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CarownerApp.vehicle')),
            ],
            options={
                'db_table': 'shedules',
            },
        ),
    ]
