# Generated by Django 4.2.5 on 2023-09-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarownerApp', '0006_rename_order_orders_alter_orders_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='email_driver',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name_driver',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
