# Generated by Django 4.2.5 on 2023-10-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarownerApp', '0007_vehicle_email_driver_vehicle_name_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='slot_vehicle',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='dropoff_datetime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pickup_datetime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='end_date_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='start_date_time',
            field=models.TimeField(null=True),
        ),
    ]
