# Generated by Django 4.2.5 on 2023-10-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarownerApp', '0010_schedules_number_of_days_schedules_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='img_vehicle',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
