# Generated by Django 4.2.5 on 2023-10-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarownerApp', '0012_orders_pickup_daytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwnerSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
