# Generated by Django 4.2.5 on 2023-10-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarownerApp', '0013_carownersession_driversession'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'custom_session',
            },
        ),
        migrations.DeleteModel(
            name='CarOwnerSession',
        ),
        migrations.DeleteModel(
            name='DriverSession',
        ),
    ]
