# Generated by Django 4.2.5 on 2023-10-13 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarownerApp', '0015_alter_customsession_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CarownerApp.schedules'),
        ),
    ]
