# Generated by Django 4.2.5 on 2023-10-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarownerApp', '0016_orders_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='label_schedule',
            field=models.IntegerField(default=1),
        ),
    ]
