# Generated by Django 4.2.5 on 2023-11-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarownerApp', '0017_schedules_label_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='state_book',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
