# Generated by Django 4.2.5 on 2023-11-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarownerApp', '0019_driver_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='state',
            field=models.CharField(default='Đang dừng', max_length=30),
        ),
    ]
