# Generated by Django 4.2.5 on 2023-09-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carowner_id', models.IntegerField()),
                ('address_driver', models.CharField(max_length=100, null=True)),
                ('phone_driver', models.IntegerField(null=True)),
                ('verify_driver', models.BooleanField(default=False)),
                ('token_driver', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField()),
                ('name_vehicle', models.CharField(max_length=255)),
                ('img_vehicle', models.ImageField(upload_to='vehicle_img/')),
                ('description', models.CharField(max_length=255)),
                ('slot_vehicle', models.IntegerField()),
                ('type_vehicle', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
    ]
