<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-09-25 08:23

from django.db import migrations, models
=======
# Generated by Django 4.2.5 on 2023-11-16 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> developer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('LoginApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> developer
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carowner_id', models.IntegerField()),
=======
            name='CustomSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(null=True)),
                ('expire_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'custom_session',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_driver', models.CharField(max_length=100, null=True)),
                ('email_driver', models.EmailField(max_length=255, null=True)),
                ('password_driver', models.CharField(max_length=255, null=True)),
>>>>>>> developer
                ('address_driver', models.CharField(max_length=100, null=True)),
                ('phone_driver', models.IntegerField(null=True)),
                ('verify_driver', models.BooleanField(default=False)),
                ('token_driver', models.CharField(blank=True, max_length=255, null=True)),
<<<<<<< HEAD
=======
                ('comfirm_account', models.BooleanField(default=False)),
                ('state', models.CharField(default='Đang dừng', max_length=30)),
                ('carowner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> developer
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('driver_id', models.IntegerField()),
                ('name_vehicle', models.CharField(max_length=255)),
                ('img_vehicle', models.ImageField(upload_to='vehicle_img/')),
                ('description', models.CharField(max_length=255)),
                ('slot_vehicle', models.IntegerField()),
                ('type_vehicle', models.CharField(max_length=255)),
=======
                ('name_vehicle', models.CharField(max_length=255)),
                ('name_driver', models.CharField(max_length=255, null=True)),
                ('email_driver', models.EmailField(max_length=254, null=True)),
                ('img_vehicle', models.ImageField(null=True, upload_to='')),
                ('description', models.CharField(max_length=255)),
                ('slot_vehicle', models.IntegerField()),
                ('type_vehicle', models.CharField(max_length=255)),
                ('driver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CarownerApp.driver')),
>>>>>>> developer
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_schedule', models.CharField(max_length=255, null=True)),
                ('slot_vehicle', models.IntegerField(null=True)),
                ('start_location', models.CharField(max_length=255, null=True)),
                ('end_location', models.CharField(max_length=255, null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('day_schedule', models.DateField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('number_of_days', models.PositiveIntegerField(default=1)),
                ('label_schedule', models.IntegerField(default=1)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CarownerApp.vehicle')),
            ],
            options={
                'db_table': 'shedules',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer_order', models.CharField(max_length=255, null=True)),
                ('name_driver_order', models.CharField(max_length=255, null=True)),
                ('name_schedule_order', models.CharField(max_length=255, null=True)),
                ('name_vehicle_order', models.CharField(max_length=255, null=True)),
                ('name_carowner_order', models.CharField(max_length=255, null=True)),
                ('carowner_id', models.IntegerField(null=True)),
                ('quantity_slot', models.IntegerField(null=True)),
                ('pickup_location', models.CharField(max_length=255, null=True)),
                ('dropoff_location', models.CharField(max_length=255, null=True)),
                ('start_date_time', models.TimeField(null=True)),
                ('dropoff_datetime', models.TimeField(null=True)),
                ('state_order', models.BooleanField(default=False)),
                ('day_schedule', models.DateField(null=True)),
                ('pickup_daytime', models.DateTimeField(null=True)),
                ('state_book', models.CharField(max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginApp.customer')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CarownerApp.schedules')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarownerApp.vehicle')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
>>>>>>> developer
    ]
