# Generated by Django 4.2.5 on 2023-11-28 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarownerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_driver', models.CharField(max_length=255, null=True)),
                ('total_income', models.IntegerField(null=True)),
                ('driver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CarownerApp.driver')),
            ],
        ),
    ]
