# Generated by Django 4.2.5 on 2023-09-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarownerApp', '0002_remove_driver_carowner_id_remove_vehicle_driver_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='comfirm_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='email_driver',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='name_driver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='password_driver',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
