# Generated by Django 4.2.5 on 2023-09-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0008_carowner_rename_ownercar_customer_and_more'),
        ('CarownerApp', '0005_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
    ]
