# Generated by Django 4.2.5 on 2023-10-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarownerApp', '0008_schedules_slot_vehicle_alter_orders_dropoff_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='pickup_datetime',
            new_name='start_date_time',
        ),
        migrations.RenameField(
            model_name='schedules',
            old_name='end_date_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='schedules',
            old_name='start_date_time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='orders',
            name='day_schedule',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='schedules',
            name='day_schedule',
            field=models.DateField(null=True),
        ),
    ]
