# Generated by Django 4.2.5 on 2023-10-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarownerApp', '0009_rename_pickup_datetime_orders_start_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='number_of_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schedules',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
