# Generated by Django 4.2.5 on 2023-10-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarownerApp', '0011_alter_vehicle_img_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pickup_daytime',
            field=models.DateTimeField(null=True),
        ),
    ]
