# Generated by Django 4.2.5 on 2023-11-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarownerApp', '0018_orders_state_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
