# Generated by Django 4.2.5 on 2023-09-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ownercar', models.CharField(max_length=255)),
                ('email_ownercar', models.EmailField(max_length=255)),
                ('passwprd_ownercar', models.CharField(max_length=255)),
                ('address_ownercar', models.CharField(max_length=100, null=True)),
                ('phone_ownercar', models.IntegerField(null=True)),
                ('verify_ownercar', models.BooleanField(default=False)),
                ('token_ownercar', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ownercar',
            },
        ),
    ]
