# Generated by Django 4.2.5 on 2023-09-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0002_ownercar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownercar',
            old_name='passwprd_ownercar',
            new_name='password_ownercar',
        ),
    ]
